//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoloMatchmaking {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Configuration : global::System.Configuration.ApplicationSettingsBase {
        
        private static Configuration defaultInstance = ((Configuration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Configuration())));
        
        public static Configuration Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27000-27200,3097")]
        public string DestinyPorts {
            get {
                return ((string)(this["DestinyPorts"]));
            }
            set {
                this["DestinyPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Destiny2SoloMMBlockOutTCP,Destiny2SoloMMBlockOutUDP,Destiny2SoloMMBlockInTCP,Dest" +
            "iny2SoloMMBlockInUDP")]
        public string DestinyNames {
            get {
                return ((string)(this["DestinyNames"]));
            }
            set {
                this["DestinyNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6672")]
        public string RockstarPorts {
            get {
                return ((string)(this["RockstarPorts"]));
            }
            set {
                this["RockstarPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RockstarSoloMMBlockOutUDP,RockstarSoloMMBlockInUDP")]
        public string RockstarNames {
            get {
                return ((string)(this["RockstarNames"]));
            }
            set {
                this["RockstarNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDestinyHotkeys {
            get {
                return ((bool)(this["EnableDestinyHotkeys"]));
            }
            set {
                this["EnableDestinyHotkeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRockstarHotkeys {
            get {
                return ((bool)(this["EnableRockstarHotkeys"]));
            }
            set {
                this["EnableRockstarHotkeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-99999999")]
        public int LastPosX {
            get {
                return ((int)(this["LastPosX"]));
            }
            set {
                this["LastPosX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-99999999")]
        public int LastPosY {
            get {
                return ((int)(this["LastPosY"]));
            }
            set {
                this["LastPosY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl")]
        public string DestinyHotkeyModifier {
            get {
                return ((string)(this["DestinyHotkeyModifier"]));
            }
            set {
                this["DestinyHotkeyModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F9")]
        public string DestinyHotkeyKey {
            get {
                return ((string)(this["DestinyHotkeyKey"]));
            }
            set {
                this["DestinyHotkeyKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl")]
        public string RockstarHotkeyModifier {
            get {
                return ((string)(this["RockstarHotkeyModifier"]));
            }
            set {
                this["RockstarHotkeyModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F10")]
        public string RockstarHotkeyKey {
            get {
                return ((string)(this["RockstarHotkeyKey"]));
            }
            set {
                this["RockstarHotkeyKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LanguageFile {
            get {
                return ((string)(this["LanguageFile"]));
            }
            set {
                this["LanguageFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Destiny2Program {
            get {
                return ((string)(this["Destiny2Program"]));
            }
            set {
                this["Destiny2Program"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1935,3097,3478-3480")]
        public string OldDestinyPorts {
            get {
                return ((string)(this["OldDestinyPorts"]));
            }
            set {
                this["OldDestinyPorts"] = value;
            }
        }
    }
}
